version: "3"
   
services:
  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgis-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - .env
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm start

volumes:
  postgis-data:
